<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="GridView.aspx.cs" Inherits="DataBoundsControlDemo.GridView" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" DataKeyNames="RollNo">
                <Columns>
                    <asp:BoundField DataField="RollNo" HeaderText="Roll No" ReadOnly="True" />
                    <asp:BoundField DataField="Name" HeaderText="Name" />
                    <asp:BoundField DataField="Course" HeaderText="Course" />

                </Columns>



            </asp:GridView>
            <asp:TextBox ID="txtRollNo" runat="server" Placeholder="Roll No" />
<asp:TextBox ID="txtName" runat="server" Placeholder="Name" />
<asp:TextBox ID="txtCourse" runat="server" Placeholder="Course" />
<asp:Button ID="btnInsert" runat="server" Text="Insert" OnClick="btnInsert_Click" />

            <br />
        </div>
    </form>
</body>
</html>
